---
- hosts: homeserver
  vars:
    nextcloud_uid: 1003
    nextcloud_gid: 1003

    nextcloud_config_dir: "/mnt/storage/Nextcloud"
    nextcloud_webui_port: 5080

    mysql_root_password: "wnbb4pTF8lkAjH8"
    mysql_database: nextcloud
    mysql_user: nextcloud
    mysql_password: "rB2lIYDaxykuvn3"

    redis_password: "AnHS0LuMIEnWMcp"

  tasks:
    - name: Install Podman
      ansible.builtin.package:
        name:
          - podman
        state: present

    - name: Create Nextcloud group
      ansible.builtin.group:
        name: nextcloud
        state: present
        gid: "{{ nextcloud_gid }}"

    - name: Create Nextcloud user
      ansible.builtin.user:
        name: nextcloud
        state: present
        system: true
        shell: /usr/sbin/nologin
        create_home: false
        uid: "{{ nextcloud_uid }}"

    - name: Create Database directory
      ansible.builtin.file:
        path: "{{ nextcloud_config_dir }}/db"
        state: directory
        owner: nextcloud
        group: nextcloud
        mode: 0755
        recurse: yes

    - name: Create HTML directory
      ansible.builtin.file:
        path: "{{ nextcloud_config_dir }}/html"
        state: directory
        owner: nextcloud
        group: nextcloud
        mode: 0755
        recurse: yes

    - name: Create Data directory
      ansible.builtin.file:
        path: "{{ nextcloud_config_dir }}/data"
        state: directory
        owner: nextcloud
        group: nextcloud
        mode: 0755
        recurse: yes

    - name: Create Caddy configuration directory
      ansible.builtin.file:
        path: "{{ nextcloud_config_dir }}/caddy/caddy_data"
        state: directory
        owner: nextcloud
        group: nextcloud
        mode: 0755
        recurse: yes

    - name: Create Nextcloud pod
      containers.podman.podman_pod:
        name: nextcloud
        ports:
          - "{{ nextcloud_webui_port }}:80" # Caddy

    - name: Create Mariadb container
      containers.podman.podman_container:
        name: nextcloud-mariadb
        image: docker.io/library/mariadb:latest
        pod: nextcloud
        state: started
        rm: true
        detach: true
        user: "{{ nextcloud_uid }}:{{ nextcloud_gid }}"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        volume:
          - "{{ nextcloud_config_dir }}/db:/var/lib/mysql"

    - name: Create Redis container
      containers.podman.podman_container:
        name: nextcloud-redis
        image: docker.io/library/redis:alpine
        pod: nextcloud
        state: started
        rm: true
        detach: true
        user: "{{ nextcloud_uid }}:{{ nextcloud_gid }}"
        command:
          - "redis-server"
          - "--requirepass"
          - "{{ redis_password }}"

    - name: Create Nextcloud-app container
      containers.podman.podman_container:
        name: nextcloud-app
        image: docker.io/library/nextcloud:fpm-alpine
        pod: nextcloud
        state: started
        rm: true
        detach: true
        user: "{{ nextcloud_uid }}:{{ nextcloud_gid }}"
        env:
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
          REDIS_HOST: "127.0.0.1"
          REDIS_HOST_PASSWORD: "{{ redis_password }}"
        volume:
          - "{{ nextcloud_config_dir }}/html:/var/www/html"
          - "{{ nextcloud_config_dir }}/data:/var/www/html/data"

    - name: Copy Caddy config to remote
      ansible.builtin.copy:
        src: nextcloud/Caddyfile
        dest: "{{ nextcloud_config_dir }}/caddy/Caddyfile"
        owner: "{{ nextcloud_uid }}"
        group: "{{ nextcloud_gid }}"
        force: yes

    - name: Create Caddy container
      containers.podman.podman_container:
        name: nextcloud-caddy
        image: docker.io/library/caddy:latest
        pod: nextcloud
        state: started
        rm: true
        detach: true
        user: "{{ nextcloud_uid }}:{{ nextcloud_gid }}"
        volume:
          - "{{ nextcloud_config_dir }}/caddy/caddy_data:/data"
          - "{{ nextcloud_config_dir }}/caddy/Caddyfile:/etc/caddy/Caddyfile"
          - "{{ nextcloud_config_dir }}/html:/var/www/html"

    - name: Generate Systemd unit file for Nextcloud pod
      containers.podman.podman_generate_systemd:
        name: nextcloud
        new: true
        dest: /etc/systemd/system

    - name: Ensure Nextcloud pod is started and enabled
      ansible.builtin.systemd:
        name: pod-nextcloud
        daemon_reload: true
        state: started
        enabled: true

